services:
  backend:
    mem_limit: 128m
    build:
      context: ./ttranking
    ports:
      - "8000:8000"
    volumes:
      - ./ttranking:/app
      - ./backups:/backups
      - ./scripts:/scripts
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "if [ ${DEBUG} = 'true' ]; then
               python manage.py runserver 0.0.0.0:8000;
             else
               gunicorn ttranking.wsgi:application --workers 3 --bind 0.0.0.0:8000;
             fi"  

  frontend:
    mem_limit: 128m
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - ./scripts:/scripts
      - frontend_node_modules:/app/node_modules
    command: >
      sh -c "if [ ${DEBUG} = 'true' ]; then
               npm run dev;
             else
               NODE_OPTIONS="--max-old-space-size=128" npm run build;
             fi"

  db:
    build:
        context: ./db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./scripts:/scripts
volumes:
    postgres_data:
    frontend_node_modules:
