name: ttranking

services:
  backend:
    build:
      context: ./ttranking
    ports:
      - "8000:8000"
    volumes:
      - ./ttranking:/app
      - ./backups:/backups
      - ./scripts:/scripts
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SECRET_KEY=django-insecure-xfbsaylhh*wxxlzs8x!kclhcdvp+jqo!fudbs(ni266o%iq*_k
      - DEBUG=True
      - DB_NAME=ttranking
      - DB_USER=root
      - DB_PASS=uwunyanichan
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - ./scripts:/scripts
      - frontend_node_modules:/app/node_modules

  db:
    build:
        context: ./db
    environment:
      POSTGRES_DB: ttranking
      POSTGRES_USER: root
      POSTGRES_PASSWORD: uwunyanichan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./scripts:/scripts
volumes:
    postgres_data:
    frontend_node_modules:
