# Generated by Django 5.1.2 on 2025-01-20 14:32

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.get_image_upload_path),
        ),
    ]
