# Generated by Django 5.0.7 on 2024-08-05 20:35

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_date_of_birth_alter_player_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='static/players/default/player.png', null=True, upload_to=players.models.get_image_upload_path),
        ),
    ]
