# Generated by Django 5.0.7 on 2024-08-05 20:36

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_alias_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.get_image_upload_path),
        ),
    ]
