# Generated by Django 5.1.2 on 2025-01-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_matches_played_remove_player_ranking_and_more'),
        ('seasons', '0003_season_doubles_points_for_loss_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerSeasonRanking',
            new_name='Ranking',
        ),
    ]
