# Generated by Django 5.1.2 on 2025-01-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_playerseasonranking_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
