# Generated by Django 5.1.2 on 2025-01-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_ranking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='player',
        ),
    ]
