# Generated by Django 5.1.2 on 2025-01-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_ranking_unique_together_remove_ranking_player'),
        ('seasons', '0003_season_doubles_points_for_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='season_rankings', to='players.player'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('player', 'season')},
        ),
    ]
