# Generated by Django 5.0.7 on 2024-08-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_created_at_player_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='updated_by',
        ),
    ]
