# Generated by Django 5.0.7 on 2024-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
