# Generated by Django 5.1.2 on 2025-02-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_remove_ranking_victories_ranking_doubles_victories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='matches_played',
        ),
        migrations.AddField(
            model_name='ranking',
            name='doubles_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='singles_matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
