# Generated by Django 5.0.7 on 2024-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_doublesmatch_matchstats_doubles_match_singlesmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublesmatch',
            name='score',
        ),
        migrations.RemoveField(
            model_name='singlesmatch',
            name='score',
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doublesmatch',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
