# Generated by Django 5.1.2 on 2025-01-26 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_doublesmatch_team1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesmatch',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
