# Generated by Django 5.0.7 on 2024-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_doublesmatch_score_remove_singlesmatch_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesmatch',
            name='winner_team',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
