# Generated by Django 5.0.7 on 2024-08-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_doublesmatch_winner_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchStats',
        ),
    ]
