# Generated by Django 5.0.7 on 2025-01-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_delete_matchstats'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesmatch',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doubles_matches', to='seasons.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='singles_matches', to='seasons.season'),
            preserve_default=False,
        ),
    ]
