# Generated by Django 5.1.2 on 2025-02-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('singles_points_for_win', models.IntegerField(blank=True, default=2)),
                ('singles_points_for_loss', models.IntegerField(blank=True, default=0)),
                ('doubles_points_for_win', models.IntegerField(blank=True, default=1)),
                ('doubles_points_for_loss', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
