# Generated by Django 5.1.2 on 2025-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_season_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='doubles_points_for_loss',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='doubles_points_for_win',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='season',
            name='singles_points_for_loss',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='singles_points_for_win',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
